devops:
  description: FPTU DSC DevOps branches
  member_username:
    - kaitoz11
    - YP2743
    - TranNgocNam2
    - dawngn
frontend:
  description: Group consist of member in DevOps branches
  member_username:
    - baolongv3
backend:
  description: Group consist of member in DevOps branchess
  member_username:
    - baolongv3

branch_leader:
  description: Group consist of all leader in all branches
  admin: true
  member_username:
    - baolongv3