devops:
  description: FPTU DSC DevOps branches
  admin: false
  member_username:
    - kaitoz11
    - YP2743
    - TranNgocNam2
    - dawngn
    - Trungtruongit
    - cuong8864
    - dinhbach306
    - MarkVoVN
    - huylinhit
    - Nonobeam
    - ChieNQuang
    - UyLeQuoc
frontend:
  description: Group consist of member in DevOps branches
  admin: false
  member_username:
    - baolongv3
backend:
  description: Group consist of member in DevOps branches
  admin: false
  member_username:
    - baolongv3

branch_leader:
  description: Group consist of all leader in all branches
  admin: true
  member_username:
    - baolongv3
