name: "Pull Request Review"
on: 
  pull_request:
    branches: 
      - "main"
jobs:
  Plan:
    uses: fptudsc/fptu-dsc-terraform-workflow-shared/.github/workflows/terraform-pr-review.yaml@main
    with:
          terraform-version: 1.3.5